
name: docs-action

on:
  push:
    branches: [ main]

jobs:
 docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: doxygen run
      run: "sudo apt-get update -yqq && sudo apt-get install doxygen && cd docs && doxygen"

    - uses: Algo-ryth-mix/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/Legion-Engine/Legion-Engine.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clear Remote Server
      uses: appleboy/ssh-action@master
      with:
        script: |
         rm -rf ~/public_html/docs
         mkdir docs || true
         #creating the folder will fail if it already exists, but we do not care about that
        host: ${{ secrets.DOCS_HOST }}
        username: ${{ secrets.DOCS_USER }}
        key: ${{ secrets.DOCS_PRIVATE_KEY }}
        port: ${{ secrets.DOCS_PORT }}

    - name: Populate Remote Server
      uses: appleboy/scp-action@master
      with:
        source: docs/build/html/*
        target: ~/public_html/docs
        host: ${{ secrets.DOCS_HOST }}
        username: ${{ secrets.DOCS_USER }}
        key: ${{ secrets.DOCS_PRIVATE_KEY }}
        port: ${{ secrets.DOCS_PORT }}
        strip_components: 3


